### ISSUE TITLE
Utiliser des inférences non déclarés

### ISSUE THREAD

**Issue by popofr13** [rezzza/RulerBundle#2]
Cas d'utilisation

Je souhaiterais définir des règles sur les headers d'un email reçus : la présence ou non d'un header et/ou la valeur d'un header

Exemple de règle concrète :

SI le header 'X-EMV-Platform' existe ALORS effectuer tel action
SI le header 'Authentication-Results ' existe
     et contient 'spf=pass' ALORS effectuer tel action

Les noms de headers sont assez volatile, et il peut-être fastidieux de les définir et maintenir dans le fichier de configuration YAML.

Il est peut-être possible de définir un 'inference' pour le nom du header, et une pour la valeur du header, et d'appliquer sur chaque header les règles. Mais cela peut-être couteux en performances et ne pas ^tre mixé avec d'autre règles au niveau de l'email.

Exemple de règle mixée :

SI le header 'X-EMV-Platform' existe et EmailSender == 'sender@domain.com' ALORS effectuer tel action.

Il faudrait peut-être définir une 'inference' comme étant un tableau associatif, et avoir les opérateurs d'assetion adéquate : clé existe, valeur de la clef, ...

J'espère que c'est assez compréhensible ;)

**Comment by shouze** [comment]
ping @stephpy @popofr13 this is a very old one... should be closed & tagged wontfix no?

**Comment by stephpy** [comment]
Les inférences ne seront peut-être pas maintenu dans une prochaine version, on peut le mettre en wontfix je pense.
